config/routes.rb
Applift::Application.routes.draw do
  devise_for :users
  
  match "/gadgets/index" => "gadgets#index", :via=>[:post]
  resources :gadgets
  resources :gadget_images

  match "/gadgets/upload/:id" => "gadgets#upload", :via=>[:post]

  root "gadgets#index"


end

app/models/gadget.rb
class Gadget < ActiveRecord::Base
	belongs_to :user
	has_many :gadget_images
	validates :name, :presence=> true
	validates :user_id, :presence=> true
end

app/models/gadget_image.rb
class GadgetImage < ActiveRecord::Base

	belongs_to :gadget
	mount_uploader :image, AppliftUploader

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :gadgets
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/gadgets_controller.rb
class GadgetsController < ApplicationController

	before_filter :authenticate_user!
	before_action :get_gadget, only: [:show, :edit, :update, :destroy, :upload]

	def index
		search = "%"+params[:search].to_s+"%"
		@gadgets = current_user.gadgets.where("name like ? or description like ?", search, search)#.page(params[:page],params[:search]).per(10)
	end

	def show
		@upload = GadgetImage.new
	end

	def new
		@gadget = Gadget.new
	end

	def create
		@gadget = Gadget.new(gadget_params)
		@gadget.user_id = current_user.id
		if @gadget.save
			redirect_to @gadget
		else
			render new_gadget_path
		end
	end

	def edit
	end

	def update
		if @gadget.update_attributes(gadget_params)
			redirect_to @gadget
		else
			render edit_gadget_path(@gadget)
		end
	end


	def destroy
		@gadget.destroy if !@gadget.nil?
		redirect_to gadgets_path
	end

	def upload
		if params[:gadget_image].blank?
			flash[:notice] = "Please select a file"
			@upload = GadgetImage.new
		else
			@upload = GadgetImage.new(params[:gadget_image].permit(:image))
			@upload.gadget_id = @gadget.id
			if @upload.save
				flash[:notice] = "Successfully uploaded"
			else
				flash[:notice] = "Error on upload"
			end
		end
		render :show
	end


private
	def gadget_params
		params.require(:gadget).permit(:name,:description)
	end

	def get_gadget
		@gadget = current_user.gadgets.find_by_id(params[:id].to_i)
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gadgets_helper.rb
module GadgetsHelper
end

app/views/gadgets/_form.html.erb
<% if @gadget.errors.any? %>
<ul>
	<% @gadget.errors.full_messages.each do |err| %>
		<li><%= err %></li>
	<% end %>
</ul>
<% end %>

<%= form_for @gadget do |f| %>
  <p><%= t("name") %></p>
  <p><%= f.text_field :name %></p>

  <p><%= t("description") %></p>
  <p><%= f.text_area :description %></p>
  <%= f.submit "Save" %>
<% end %>

app/views/gadgets/edit.html.erb
<h1>Edit gadget : <%= @gadget.name %> </h1>

<%= render partial: "/gadgets/form" %>

app/views/gadgets/index.html.erb
<h1>Gadget index</h1>

<%= form_tag "/gadgets/index" do %>
<input type="text" placeholder="name, description" name="search" value="<%= params[:search] %>">&nbsp;
<input type="submit" class="btn btn-primary" value="Search">
<% end %>


<%= link_to "Add gadget" , new_gadget_path, :class=>"btn btn-primary" %>
<table class="table table-bordered"> 
<thead>
	<tr>
		<th>Name</th>
		<th>Description</th>
		<th># images</th>
		<th>Actions</th>
	</tr>
</thead>
<tbody>
<% @gadgets.each do |res| %>
	<tr>
		<td><%= res.name %></td>
		<td><%= res.description %></td>
		<td>
			<% res.gadget_images.each do |img| %>
			<%= link_to( image_tag(img.image.thumb,:width=>"50px;"), img.image.standard.url ) %>
			<% end %>
		</td>
		<td>
			<%= link_to "View" , gadget_path(res) %>&nbsp;&nbsp;
			<%= link_to "Edit" , edit_gadget_path(res) %>&nbsp;&nbsp;
			<%= link_to "Delete" , res , :method=>:delete, :title=>"Delete", :confirm=>"Delete gadget: #{res.name}?" %>&nbsp;
		</td>
	</tr>
<% end %>
</tbody>
</table>
<%# paginate @gadgets %>

app/views/gadgets/new.html.erb
<h1>New gadget</h1>

<%= render partial: "/gadgets/form" %>

app/views/gadgets/show.html.erb
<h1><%= @gadget.name %></h1>
<p><%= @gadget.description %></p>
<h2>Images</h2>
<% @gadget.gadget_images.each do |res| %>
		<%= link_to( image_tag(res.image.medium), res.image.standard.url ) %>
<% end %> 

<%= form_for @upload, :url=>"/gadgets/upload/#{@gadget.id}" do |f|%>
	<%= f.file_field :image %>
	<%= f.submit "Upload" %>
<% end %>

<%= link_to "Edit", edit_gadget_path(@gadget) %><br/>
<%= link_to "Back to index" , gadgets_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Applift</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if current_user %>
	<div><%= link_to "Logout", destroy_user_session_path, method: "delete" %></div>
<% end %>

<% if !flash[:notice].blank? %>
		<div style="color:red;font-size:22px;"><%= flash[:notice] %></div>
<% end %>

<%= yield %>

</body>
</html>